// Generated by Apple Swift version 2.1.1 (swiftlang-700.1.101.15 clang-700.1.81)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
#endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import Foundation;
#endif

#import <PredixMobileSDK/PredixMobileSDK.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class NSURLRequest;
@class NSHTTPURLResponse;

SWIFT_PROTOCOL("_TtP15PredixMobileSDK15ServiceProtocol_")
@protocol ServiceProtocol
+ (NSString * __nonnull)serviceIdentifier;
+ (void)performRequest:(NSURLRequest * __nonnull)request response:(NSHTTPURLResponse * __nonnull)response responseReturn:(responseReturnBlock __nonnull)responseReturn dataReturn:(dataReturnBlock __nonnull)dataReturn requestComplete:(requestCompleteBlock __nonnull)requestComplete;
@optional
+ (void)registered;
+ (void)unregistered;
@end


SWIFT_CLASS("_TtC15PredixMobileSDK10CDBService")
@interface CDBService : NSObject <ServiceProtocol>
+ (NSString * __nonnull)serviceIdentifier;
+ (void)performRequest:(NSURLRequest * __nonnull)request response:(NSHTTPURLResponse * __nonnull)response responseReturn:(responseReturnBlock __nonnull)responseReturn dataReturn:(dataReturnBlock __nonnull)dataReturn requestComplete:(requestCompleteBlock __nonnull)requestComplete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ConfigurationLocation) {
  ConfigurationLocationsettings = 0,
  ConfigurationLocationinfoplist = 1,
};


SWIFT_CLASS("_TtC15PredixMobileSDK19ConnectivityService")
@interface ConnectivityService : NSObject <ServiceProtocol>
+ (NSString * __nonnull)serviceIdentifier;
+ (void)performRequest:(NSURLRequest * __nonnull)request response:(NSHTTPURLResponse * __nonnull)response responseReturn:(responseReturnBlock __nonnull)responseReturn dataReturn:(dataReturnBlock __nonnull)dataReturn requestComplete:(requestCompleteBlock __nonnull)requestComplete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PredixMobileSDK9DBService")
@interface DBService : NSObject <ServiceProtocol>
+ (NSString * __nonnull)serviceIdentifier;
+ (void)performRequest:(NSURLRequest * __nonnull)request response:(NSHTTPURLResponse * __nonnull)response responseReturn:(responseReturnBlock __nonnull)responseReturn dataReturn:(dataReturnBlock __nonnull)dataReturn requestComplete:(requestCompleteBlock __nonnull)requestComplete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PredixMobileSDK10LogService")
@interface LogService : NSObject <ServiceProtocol>
+ (NSString * __nonnull)serviceIdentifier;
+ (void)performRequest:(NSURLRequest * __nonnull)request response:(NSHTTPURLResponse * __nonnull)response responseReturn:(responseReturnBlock __nonnull)responseReturn dataReturn:(dataReturnBlock __nonnull)dataReturn requestComplete:(requestCompleteBlock __nonnull)requestComplete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface NSCharacterSet (SWIFT_EXTENSION(PredixMobileSDK))
@end


SWIFT_CLASS("_TtC15PredixMobileSDK13NotifyService")
@interface NotifyService : NSObject <ServiceProtocol>
+ (NSString * __nonnull)serviceIdentifier;
+ (void)performRequest:(NSURLRequest * __nonnull)request response:(NSHTTPURLResponse * __nonnull)response responseReturn:(responseReturnBlock __nonnull)responseReturn dataReturn:(dataReturnBlock __nonnull)dataReturn requestComplete:(requestCompleteBlock __nonnull)requestComplete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PredixMobileSDK14OpenURLService")
@interface OpenURLService : NSObject <ServiceProtocol>
+ (NSString * __nonnull)serviceIdentifier;
+ (void)performRequest:(NSURLRequest * __nonnull)request response:(NSHTTPURLResponse * __nonnull)response responseReturn:(responseReturnBlock __nonnull)responseReturn dataReturn:(dataReturnBlock __nonnull)dataReturn requestComplete:(requestCompleteBlock __nonnull)requestComplete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface PGSDKLogger (SWIFT_EXTENSION(PredixMobileSDK))
@end

@class NSURL;
enum WaitState : NSInteger;
@class WaitStateReturn;

SWIFT_PROTOCOL("_TtP15PredixMobileSDK23PredixAppWindowProtocol_")
@protocol PredixAppWindowProtocol
- (void)loadURL:(NSURL * __nonnull)URL parameters:(NSDictionary * __nullable)parameters onComplete:(void (^ __nullable)(void))onComplete;
- (void)updateWaitState:(enum WaitState)state message:(NSString * __nullable)message;
- (WaitStateReturn * __nonnull)waitState;
@optional
- (void)receiveAppNotification:(NSString * __nonnull)script;
@end


SWIFT_CLASS("_TtC15PredixMobileSDK27PredixMobilityConfiguration")
@interface PredixMobilityConfiguration : NSObject
+ (PGSDKLoggerLevelEnum)defaultLoggingLevel;
+ (void)setDefaultLoggingLevel:(PGSDKLoggerLevelEnum)value;
+ (NSString * __nonnull)defaultDatabaseName;
+ (void)setDefaultDatabaseName:(NSString * __nonnull)value;
+ (NSString * __nonnull)authenticationScheme;
+ (void)setAuthenticationScheme:(NSString * __nonnull)value;
+ (NSString * __nonnull)authenticationGrantIndicator;
+ (void)setAuthenticationGrantIndicator:(NSString * __nonnull)value;
+ (NSString * __nonnull)loggingLevelConfigKey;
+ (void)setLoggingLevelConfigKey:(NSString * __nonnull)value;
+ (enum ConfigurationLocation)loggingLevelConfigLocation;
+ (void)setLoggingLevelConfigLocation:(enum ConfigurationLocation)value;
+ (NSString * __nonnull)traceLogsRequestsConfigKey;
+ (void)setTraceLogsRequestsConfigKey:(NSString * __nonnull)value;
+ (enum ConfigurationLocation)traceLogsRequestsConfigLocation;
+ (void)setTraceLogsRequestsConfigLocation:(enum ConfigurationLocation)value;
+ (NSString * __nonnull)serverEndpointConfigKey;
+ (void)setServerEndpointConfigKey:(NSString * __nonnull)value;
+ (enum ConfigurationLocation)serverEndpointConfigLocation;
+ (void)setServerEndpointConfigLocation:(enum ConfigurationLocation)value;
+ (NSString * __nonnull)userSessionURLPath;
+ (void)setUserSessionURLPath:(NSString * __nonnull)value;
+ (NSString * __nonnull)loginURLPath;
+ (void)setLoginURLPath:(NSString * __nonnull)value;
+ (NSString * __nonnull)logoutURLPath;
+ (void)setLogoutURLPath:(NSString * __nonnull)value;
+ (NSString * __nonnull)dataReplicationURLPath;
+ (void)setDataReplicationURLPath:(NSString * __nonnull)value;
+ (NSString * __nonnull)authorizationCheckURLPath;
+ (void)setAuthorizationCheckURLPath:(NSString * __nonnull)value;
+ (NSString * __nonnull)userSessionUsernameKey;
+ (void)setUserSessionUsernameKey:(NSString * __nonnull)value;
+ (NSString * __nonnull)userSessionAuthenticatedKey;
+ (void)setUserSessionAuthenticatedKey:(NSString * __nonnull)value;
+ (NSString * __nullable)userSessionDatabaseNameKey;
+ (void)setUserSessionDatabaseNameKey:(NSString * __nullable)value;
+ (NSString * __nonnull)pmappDocumentNameKey;
+ (void)setPmappDocumentNameKey:(NSString * __nonnull)value;
+ (enum ConfigurationLocation)pmappDocumentNameConfigLocation;
+ (void)setPmappDocumentNameConfigLocation:(enum ConfigurationLocation)value;
+ (NSString * __nonnull)pmappDocumentVersionKey;
+ (void)setPmappDocumentVersionKey:(NSString * __nonnull)value;
+ (enum ConfigurationLocation)pmappDocumentVersionConfigLocation;
+ (void)setPmappDocumentVersionConfigLocation:(enum ConfigurationLocation)value;
+ (NSString * __nonnull)pmAppDocumentWebAppNameKey;
+ (void)setPmAppDocumentWebAppNameKey:(NSString * __nonnull)value;
+ (NSString * __nonnull)pmAppDocumentOfflineAppNameKey;
+ (void)setPmAppDocumentOfflineAppNameKey:(NSString * __nonnull)value;
+ (NSString * __nonnull)pmAppDocumentDependenciesKey;
+ (void)setPmAppDocumentDependenciesKey:(NSString * __nonnull)value;
+ (NSString * __nonnull)API_HOST;
+ (void)setAPI_HOST:(NSString * __nonnull)value;
+ (NSString * __nonnull)seriousErrorDefaultMessage;
+ (void)setSeriousErrorDefaultMessage:(NSString * __nonnull)value;
+ (NSString * __nonnull)seriousErrorPage;
+ (void)setSeriousErrorPage:(NSString * __nonnull)value;
+ (void (^ __nullable)(void (^ __nonnull)(void)))additionalBootRestartWorkflow;
+ (void)setAdditionalBootRestartWorkflow:(void (^ __nullable)(void (^ __nonnull)(void)))value;
+ (NSArray<Class <ServiceProtocol>> * __nullable)additionalBootServicesToRegister;
+ (void)setAdditionalBootServicesToRegister:(NSArray<Class <ServiceProtocol>> * __nullable)value;
+ (BOOL)shouldLogUnhandledErrors;
+ (void)setShouldLogUnhandledErrors:(BOOL)value;
+ (BOOL)shouldInitializeDefaultsFromSettings;
+ (void)setShouldInitializeDefaultsFromSettings:(BOOL)value;
+ (BOOL)shouldIssueWarningsForPlaceholderURLs;
+ (void)setShouldIssueWarningsForPlaceholderURLs:(BOOL)value;
+ (NSString * __nonnull)defaultInitializationDetectionKey;
+ (void)setDefaultInitializationDetectionKey:(NSString * __nonnull)value;
+ (BOOL)traceLogsAllRequestsDefault;
+ (void)setTraceLogsAllRequestsDefault:(BOOL)value;
+ (NSDictionary<NSString *, id> * __nullable)remoteNotificationRegistrationAdditionalInfo;
+ (void)setRemoteNotificationRegistrationAdditionalInfo:(NSDictionary<NSString *, id> * __nullable)value;
+ (NSString * __nonnull)remoteNotificationRegistrationDocumentId;
+ (void)setRemoteNotificationRegistrationDocumentId:(NSString * __nonnull)value;
+ (NSString * __nonnull)remoteNotificationRegistrationDocumentType;
+ (void)setRemoteNotificationRegistrationDocumentType:(NSString * __nonnull)value;
+ (NSString * __nullable)keychainAccessGroup;
+ (void)setKeychainAccessGroup:(NSString * __nullable)value;
+ (NSString * __nonnull)keychainKeyPrefix;
+ (void)setKeychainKeyPrefix:(NSString * __nonnull)value;
+ (NSString * __nonnull)versionInfo;
+ (NSURL * __nonnull)localStorageURL;
+ (NSURL * __nullable)userLocalStorageURL;
+ (void)loadConfiguration;
+ (void)appendDataViewDefinition:(NSString * __nonnull)viewName version:(NSString * __nonnull)version mapFunction:(void (^ __nonnull)(NSDictionary<NSString *, id> * __nonnull, void (^ __nonnull)(id __nonnull, id __nullable)))mapFunction;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNotification;
@class UIApplication;
@class UILocalNotification;
@class NSData;
@class NSError;

SWIFT_CLASS("_TtC15PredixMobileSDK21PredixMobilityManager")
@interface PredixMobilityManager : NSObject
+ (PredixMobilityManager * __nonnull)sharedInstance;
@property (nonatomic, strong) id <PredixAppWindowProtocol> __nonnull packageWindow;
@property (nonatomic, copy) id <PredixAppWindowProtocol> __nonnull (^ __nonnull presentAuthentication)(id <PredixAppWindowProtocol> __nonnull);
@property (nonatomic, copy) void (^ __nonnull dismissAuthentication)(id <PredixAppWindowProtocol> __nonnull);
@property (nonatomic, copy) NSArray<NSDictionary<NSString *, id> *> * __nullable localOrRemoteNotifications;
@property (nonatomic, readonly) BOOL isShowingAuthentication;
@property (nonatomic, readonly, strong) id <PredixAppWindowProtocol> __nonnull currentWindow;
- (nonnull instancetype)initWithPackageWindow:(id <PredixAppWindowProtocol> __nonnull)packageWindow presentAuthentication:(id <PredixAppWindowProtocol> __nonnull (^ __nonnull)(id <PredixAppWindowProtocol> __nonnull))presentAuthentication dismissAuthentication:(void (^ __nonnull)(id <PredixAppWindowProtocol> __nonnull))dismissAuthentication OBJC_DESIGNATED_INITIALIZER;
- (void)showAuthentication:(NSURL * __nonnull)URL onComplete:(void (^ __nullable)(void))onComplete;
- (void)authenticationComplete;
- (void)showPackageWindow:(NSURL * __nonnull)URL parameters:(NSDictionary * __nullable)parameters onComplete:(void (^ __nullable)(void))onComplete;
- (void)startApp;
- (void)callBootService;
- (void)ShowUserError:(NSString * __nonnull)msg;
- (void)addTranslationForNotification:(NSString * __nonnull)originalNotificationName asNotificationName:(NSString * __nonnull)asNotificationName translation:(NSDictionary<NSString *, id> * __nullable (^ __nonnull)(NSNotification * __nonnull))translation;
- (void)removeTranslationForNotificationName:(NSString * __nonnull)notificationName;
- (void)applicationWillResignActive:(UIApplication * __nonnull)application;
- (void)applicationDidEnterBackground:(UIApplication * __nonnull)application;
- (void)applicationWillEnterForeground:(UIApplication * __nonnull)application;
- (void)applicationDidBecomeActive:(UIApplication * __nonnull)application;
- (void)applicationWillTerminate:(UIApplication * __nonnull)application;
- (void)application:(UIApplication * __nonnull)application didReceiveLocalNotification:(UILocalNotification * __nonnull)notification;
- (void)application:(UIApplication * __nonnull)application didReceiveRemoteNotification:(NSDictionary * __nonnull)userInfo;
- (void)application:(UIApplication * __nonnull)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData * __nonnull)deviceToken;
- (void)application:(UIApplication * __nonnull)application didFailToRegisterForRemoteNotificationsWithError:(NSError * __nonnull)error;
@end


SWIFT_CLASS("_TtC15PredixMobileSDK25ReachabilityStatusWrapper")
@interface ReachabilityStatusWrapper : NSObject
@property (nonatomic, readonly, copy) NSString * __nonnull description;
@end



SWIFT_PROTOCOL("_TtP15PredixMobileSDK21ServiceRouterProtocol_")
@protocol ServiceRouterProtocol
- (BOOL)registerService:(Class <ServiceProtocol> __nonnull)service;
- (void)unregisterService:(Class <ServiceProtocol> __nonnull)service;
- (void)processRequest:(NSURLRequest * __nonnull)request responseBlock:(responseReturnBlock __nonnull)responseBlock dataBlock:(dataReturnBlock __nonnull)dataBlock completionBlock:(requestCompleteBlock __nonnull)completionBlock;
- (void)processRequestWithServiceId:(NSString * __nonnull)serviceId responseBlock:(responseReturnBlock __nonnull)responseBlock dataBlock:(dataReturnBlock __nonnull)dataBlock completionBlock:(requestCompleteBlock __nonnull)completionBlock;
- (void)processRequest:(NSString * __nonnull)serviceId extraPath:(NSString * __nullable)extraPath responseBlock:(responseReturnBlock __nonnull)responseBlock dataBlock:(dataReturnBlock __nonnull)dataBlock completionBlock:(requestCompleteBlock __nonnull)completionBlock;
- (void)processRequest:(NSString * __nonnull)serviceId extraPath:(NSString * __nullable)extraPath method:(NSString * __nonnull)method data:(NSData * __nullable)data responseBlock:(responseReturnBlock __nonnull)responseBlock dataBlock:(dataReturnBlock __nonnull)dataBlock completionBlock:(requestCompleteBlock __nonnull)completionBlock;
@end


SWIFT_CLASS("_TtC15PredixMobileSDK13ServiceRouter")
@interface ServiceRouter : NSObject <ServiceRouterProtocol>
+ (id <ServiceRouterProtocol> __nonnull)sharedInstance;
- (BOOL)registerService:(Class <ServiceProtocol> __nonnull)service;
- (void)unregisterService:(Class <ServiceProtocol> __nonnull)service;
- (void)processRequestWithServiceId:(NSString * __nonnull)serviceId responseBlock:(responseReturnBlock __nonnull)responseBlock dataBlock:(dataReturnBlock __nonnull)dataBlock completionBlock:(requestCompleteBlock __nonnull)completionBlock;
- (void)processRequest:(NSString * __nonnull)serviceId extraPath:(NSString * __nullable)extraPath responseBlock:(responseReturnBlock __nonnull)responseBlock dataBlock:(dataReturnBlock __nonnull)dataBlock completionBlock:(requestCompleteBlock __nonnull)completionBlock;
- (void)processRequest:(NSString * __nonnull)serviceId extraPath:(NSString * __nullable)extraPath method:(NSString * __nonnull)method data:(NSData * __nullable)data responseBlock:(responseReturnBlock __nonnull)responseBlock dataBlock:(dataReturnBlock __nonnull)dataBlock completionBlock:(requestCompleteBlock __nonnull)completionBlock;
- (void)processRequest:(NSURLRequest * __nonnull)request responseBlock:(responseReturnBlock __nonnull)responseBlock dataBlock:(dataReturnBlock __nonnull)dataBlock completionBlock:(requestCompleteBlock __nonnull)completionBlock;
@end



SWIFT_CLASS("_TtC15PredixMobileSDK11UserService")
@interface UserService : NSObject <ServiceProtocol>
+ (NSString * __nonnull)serviceIdentifier;
+ (void)performRequest:(NSURLRequest * __nonnull)request response:(NSHTTPURLResponse * __nonnull)response responseReturn:(responseReturnBlock __nonnull)responseReturn dataReturn:(dataReturnBlock __nonnull)dataReturn requestComplete:(requestCompleteBlock __nonnull)requestComplete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PredixMobileSDK19UserSettingsService")
@interface UserSettingsService : NSObject <ServiceProtocol>
+ (NSString * __nonnull)serviceIdentifier;
+ (void)performRequest:(NSURLRequest * __nonnull)request response:(NSHTTPURLResponse * __nonnull)response responseReturn:(responseReturnBlock __nonnull)responseReturn dataReturn:(dataReturnBlock __nonnull)dataReturn requestComplete:(requestCompleteBlock __nonnull)requestComplete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, WaitState) {
  WaitStateWaiting = 0,
  WaitStateNotWaiting = 1,
};


SWIFT_CLASS("_TtC15PredixMobileSDK15WaitStateReturn")
@interface WaitStateReturn : NSObject
- (nonnull instancetype)initWithState:(enum WaitState)state message:(NSString * __nullable)message OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(enum WaitState)state :(NSString * __nullable)message OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithState:(enum WaitState)state OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(enum WaitState)state OBJC_DESIGNATED_INITIALIZER;
@end

#pragma clang diagnostic pop
